### PR TITLE
41 make category optional

### PR DESCRIPTION
**Pull request by nilsalm**
BREAKING: import the updated schema to your local DB
Left TODO: update the schema (and version) in fly.io

### CODE REVIEW

**Comment by nilsalm** [comment]
Uploading Screen Recording 2023-05-05 at 09.31.21.mov…

**Comment by nilsalm** [comment]
https://user-images.githubusercontent.com/16445336/236400578-9e4e82a9-1c0d-4b5c-9473-b6db21af977f.mov

**Comment by nilsalm** [comment]
Now that i think about it, it would be EVEN nicer to be able to drag and drop an item into another category and update the category like so. Then we could skip the extra button too.

**Review by brokelyn — APPROVED** [review]
Sweet :rocket: 

I think we should start refactoring things in their own component from now on when files exceed over maybe 100lines or 150 lines?

**Comment by nilsalm** [comment]
Great idea!

**Pull request merged**
